export enum DungeonId {
  HyruleCastle,
  CastleTower,
  EasternPalace,
  DesertPalace,
  TowerOfHera,
  PalaceOfDarkness,
  SwampPalace,
  SkullWoods,
  ThievesTown,
  IcePalace,
  MiseryMire,
  TurtleRock,
  GanonsTower,
}
