import Inventory from './inventory';
import InventoryId from './inventory-id';

const fallbackInventory: Inventory = {};
fallbackInventory[InventoryId.Bow] = 0;
fallbackInventory[InventoryId.SilverArrows] = 0;
fallbackInventory[InventoryId.BlueBoomerang] = 0;
fallbackInventory[InventoryId.RedBoomerang] = 0;
fallbackInventory[InventoryId.Hookshot] = 0;
fallbackInventory[InventoryId.Bomb] = 0;
fallbackInventory[InventoryId.Mushroom] = 0;
fallbackInventory[InventoryId.Powder] = 0;
fallbackInventory[InventoryId.FireRod] = 0;
fallbackInventory[InventoryId.IceRod] = 0;
fallbackInventory[InventoryId.Bombos] = 0;
fallbackInventory[InventoryId.Ether] = 0;
fallbackInventory[InventoryId.Quake] = 0;
fallbackInventory[InventoryId.Magic] = 0;
fallbackInventory[InventoryId.Lantern] = 0;
fallbackInventory[InventoryId.Hammer] = 0;
fallbackInventory[InventoryId.Flute] = 0;
fallbackInventory[InventoryId.Net] = 0;
fallbackInventory[InventoryId.Book] = 0;
fallbackInventory[InventoryId.Tunic] = 0;
fallbackInventory[InventoryId.Bottle] = 0;
fallbackInventory[InventoryId.Somaria] = 0;
fallbackInventory[InventoryId.Byrna] = 0;
fallbackInventory[InventoryId.Cape] = 0;
fallbackInventory[InventoryId.Mirror] = 0;
fallbackInventory[InventoryId.Shield] = 0;
fallbackInventory[InventoryId.Shovel] = 0;
fallbackInventory[InventoryId.Boots] = 0;
fallbackInventory[InventoryId.Glove] = 0;
fallbackInventory[InventoryId.Flippers] = 0;
fallbackInventory[InventoryId.MoonPearl] = 0;
fallbackInventory[InventoryId.Sword] = 0;
fallbackInventory[InventoryId.HeartContainer] = 3;

export { fallbackInventory };
